// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: pb/svc/apid/apid.proto

package apid

import (
	article "github.com/aglide100/db-datasvc-example/pb/unit/article"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetArticleListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetArticleListReq) Reset() {
	*x = GetArticleListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_apid_apid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArticleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleListReq) ProtoMessage() {}

func (x *GetArticleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_apid_apid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleListReq.ProtoReflect.Descriptor instead.
func (*GetArticleListReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_apid_apid_proto_rawDescGZIP(), []int{0}
}

func (x *GetArticleListReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetArticleListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Article []*article.Article `protobuf:"bytes,1,rep,name=article,proto3" json:"article,omitempty"`
}

func (x *GetArticleListRes) Reset() {
	*x = GetArticleListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_apid_apid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArticleListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleListRes) ProtoMessage() {}

func (x *GetArticleListRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_apid_apid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleListRes.ProtoReflect.Descriptor instead.
func (*GetArticleListRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_apid_apid_proto_rawDescGZIP(), []int{1}
}

func (x *GetArticleListRes) GetArticle() []*article.Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type AddArticleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Article *article.Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
}

func (x *AddArticleReq) Reset() {
	*x = AddArticleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_apid_apid_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticleReq) ProtoMessage() {}

func (x *AddArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_apid_apid_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticleReq.ProtoReflect.Descriptor instead.
func (*AddArticleReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_apid_apid_proto_rawDescGZIP(), []int{2}
}

func (x *AddArticleReq) GetArticle() *article.Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type AddArticleRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AddArticleRes) Reset() {
	*x = AddArticleRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_apid_apid_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddArticleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticleRes) ProtoMessage() {}

func (x *AddArticleRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_apid_apid_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticleRes.ProtoReflect.Descriptor instead.
func (*AddArticleRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_apid_apid_proto_rawDescGZIP(), []int{3}
}

func (x *AddArticleRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_svc_apid_apid_proto protoreflect.FileDescriptor

var file_pb_svc_apid_apid_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x64, 0x2f, 0x61, 0x70,
	0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63,
	0x2e, 0x61, 0x70, 0x69, 0x64, 0x1a, 0x1d, 0x70, 0x62, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x2f, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x32,
	0x0a, 0x07, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x62, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x07, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x22, 0x43, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x07, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x07,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x22, 0x21, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xa5, 0x01, 0x0a, 0x0b, 0x41,
	0x70, 0x69, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x70,
	0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x70,
	0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x0a,
	0x41, 0x64, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e,
	0x73, 0x76, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e,
	0x61, 0x70, 0x69, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x67, 0x6c, 0x69, 0x64, 0x65, 0x31, 0x30, 0x30, 0x2f, 0x64, 0x62, 0x2d, 0x64, 0x61,
	0x74, 0x61, 0x73, 0x76, 0x63, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x62,
	0x2f, 0x73, 0x76, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pb_svc_apid_apid_proto_rawDescOnce sync.Once
	file_pb_svc_apid_apid_proto_rawDescData = file_pb_svc_apid_apid_proto_rawDesc
)

func file_pb_svc_apid_apid_proto_rawDescGZIP() []byte {
	file_pb_svc_apid_apid_proto_rawDescOnce.Do(func() {
		file_pb_svc_apid_apid_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_svc_apid_apid_proto_rawDescData)
	})
	return file_pb_svc_apid_apid_proto_rawDescData
}

var file_pb_svc_apid_apid_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_svc_apid_apid_proto_goTypes = []interface{}{
	(*GetArticleListReq)(nil), // 0: pb.svc.apid.GetArticleListReq
	(*GetArticleListRes)(nil), // 1: pb.svc.apid.GetArticleListRes
	(*AddArticleReq)(nil),     // 2: pb.svc.apid.AddArticleReq
	(*AddArticleRes)(nil),     // 3: pb.svc.apid.AddArticleRes
	(*article.Article)(nil),   // 4: pb.unit.article.Article
}
var file_pb_svc_apid_apid_proto_depIdxs = []int32{
	4, // 0: pb.svc.apid.GetArticleListRes.article:type_name -> pb.unit.article.Article
	4, // 1: pb.svc.apid.AddArticleReq.article:type_name -> pb.unit.article.Article
	0, // 2: pb.svc.apid.ApidService.GetArticleList:input_type -> pb.svc.apid.GetArticleListReq
	2, // 3: pb.svc.apid.ApidService.AddArticle:input_type -> pb.svc.apid.AddArticleReq
	1, // 4: pb.svc.apid.ApidService.GetArticleList:output_type -> pb.svc.apid.GetArticleListRes
	3, // 5: pb.svc.apid.ApidService.AddArticle:output_type -> pb.svc.apid.AddArticleRes
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_svc_apid_apid_proto_init() }
func file_pb_svc_apid_apid_proto_init() {
	if File_pb_svc_apid_apid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_svc_apid_apid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArticleListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_apid_apid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArticleListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_apid_apid_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddArticleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_apid_apid_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddArticleRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_svc_apid_apid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_svc_apid_apid_proto_goTypes,
		DependencyIndexes: file_pb_svc_apid_apid_proto_depIdxs,
		MessageInfos:      file_pb_svc_apid_apid_proto_msgTypes,
	}.Build()
	File_pb_svc_apid_apid_proto = out.File
	file_pb_svc_apid_apid_proto_rawDesc = nil
	file_pb_svc_apid_apid_proto_goTypes = nil
	file_pb_svc_apid_apid_proto_depIdxs = nil
}
