version: "3.5"
services:
    db:
        build:
            context: ../../
            dockerfile: ./cmd/db/Dockerfile
        hostname: db
        networks:
            - docker-network
        ports:
            - 8432:5432
        environment:
            #PGDATA: /var/lib/postgresql/data
            POSTGRES_DB: mydb
            #POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_USER: table_admin
            POSTGRES_PASSWORD: HelloWorld
            POSTGRES_INITDB_ARGS: --encoding=UTF-8
networks:
    docker-network:
        driver: bridge
